name: 'proyecto_atp'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  proyecto_atp:
    # Capa de staging
    staging:
      +materialized: view
      +database: ALUMNO26_DEV_SILVER_DB_ATP
      +schema: pfranco

    # Capa de mart (Gold)
    marts:
      +materialized: table
      +database: ALUMNO26_DEV_GOLD_DB_ATP
      +schema: pfranco
      +on_schema_change: fail
